export const LANG_PAIRS = [
  // Anglais → autres
  'English → Arabic',
  'English → Bulgarian',
  'English → Chinese (Simplified)',
  'English → Chinese (Traditional)',
  'English → Czech',
  'English → Danish',
  'English → Dutch',
  'English → Estonian',
  'English → Finnish',
  'English → French',
  'English → German',
  'English → Greek',
  'English → Hebrew',
  'English → Hungarian',
  'English → Indonesian',
  'English → Italian',
  'English → Japanese',
  'English → Korean',
  'English → Malay',
  'English → Norwegian',
  'English → Polish',
  'English → Portuguese',
  'English → Romanian',
  'English → Russian',
  'English → Slovenian',
  'English → Spanish',
  'English → Swedish',
  'English → Thai',
  'English → Turkish',
  'English → Ukrainian',
  'English → Vietnamese',
  // Autres → Anglais
  'Arabic → English',
  'Chinese → English',
  'Czech → English',
  'Dutch → English',
  'French → English',
  'German → English',
  'Italian → English',
  'Japanese → English',
  'Korean → English',
  'Polish → English',
  'Portuguese → English',
  'Romanian → English',
  'Russian → English',
  'Spanish → English',
  'Turkish → English',
  'Ukrainian → English',
  // Autres paires
  'Dutch → Ukrainian',
  'Dutch → French',
  'French → Spanish',
  'French → German',
  'German → French',
  'Spanish → French',
  'Spanish → Portuguese',
  'Portuguese → Spanish',
];
